#!/bin/bash
# Build Lambda Layer: pandas + numpy (arm64, Python 3.14)
# Dependency layer for EnrichmentFunction -- the only function that loads it.
# Usage:  ./build-layer.sh
# Output: layers/pandas-numpy-layer.zip
#
# Run this WHENEVER the Lambda runtime changes. `sam build` does NOT rebuild
# the layer -- it passes the zip through by ContentUri reference -- so a green
# build says nothing about layer correctness. Also required on any fresh clone,
# since layers/*.zip is gitignored.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LAYER_DIR="${SCRIPT_DIR}/layers/pandas-numpy"
PYTHON_DIR="${LAYER_DIR}/python/lib/python3.14/site-packages"
OUTPUT_ZIP="${SCRIPT_DIR}/layers/pandas-numpy-layer.zip"

echo "============================================================"
echo "Building pandas/numpy Lambda Layer"
echo "Target: Python 3.14, arm64 (manylinux_2_28_aarch64)"
echo "============================================================"

# Clean previous build
rm -rf "${LAYER_DIR}"
rm -f "${OUTPUT_ZIP}"
mkdir -p "${PYTHON_DIR}"

# Install for Lambda arm64 architecture.
# Versions are pinned because the CPython 3.14 (cp314) wheel is the
# constraint: pandas gained cp314 wheels at 2.3.3 and numpy at 2.3.3,
# so the previous 2.3.2/2.2.6 pair cannot build for this runtime.
# manylinux_2_28 is required -- the cp314 wheels are published as
# manylinux_2_28_aarch64, and the old manylinux2014 tag alone resolves
# to nothing. Amazon Linux 2023 provides glibc 2.34, so 2.28 is safe.
echo ""
echo "Installing pandas + numpy..."
pip install \
    --platform manylinux_2_28_aarch64 \
    --platform manylinux2014_aarch64 \
    --target "${PYTHON_DIR}" \
    --implementation cp \
    --python-version 3.14 \
    --only-binary=:all: \
    --no-deps \
    "pandas==2.3.3" \
    "numpy==2.3.3" \
    "pytz==2025.2" \
    "python-dateutil==2.9.0.post0" \
    "six==1.17.0"

echo ""

# Strip __pycache__ directories.
#
# pip byte-compiles with the LOCAL interpreter, not the --python-version
# target, so on a machine running Python 3.13 the wheels get .pyc files
# tagged cpython-313 even though every .so is correctly cpython-314. The
# 2026-08-02 build shipped 1,849 such files.
#
# They are harmless -- CPython ignores a .pyc whose magic number does not
# match the running interpreter and recompiles from source -- but they are
# dead weight in a layer that counts against the 250MB unzipped limit, and
# they make ABI verification of the artifact confusing (a naive
# `unzip -l | grep cpython-3..` shows two different tags).
#
# Removing them costs a small one-time import penalty on cold start as
# Lambda recompiles from source. Lambda's filesystem is read-only, so the
# regenerated bytecode is not cached between invocations either way.
echo "Stripping __pycache__ (pip compiles with the local interpreter, not 3.14)..."
PYCACHE_COUNT=$(find "${PYTHON_DIR}" -name '__pycache__' -type d | wc -l | tr -d ' ')
find "${PYTHON_DIR}" -name '__pycache__' -type d -prune -exec rm -rf {} +
echo "  Removed ${PYCACHE_COUNT} __pycache__ directories"

# Fail loudly if any compiled extension carries the wrong CPython ABI tag.
# A .so built for the wrong version imports fine locally and fails only at
# Lambda invocation time, which is the most expensive place to find out.
echo ""
echo "Verifying .so ABI tags..."
WRONG_ABI=$(find "${PYTHON_DIR}" -name '*.so' | grep -oE 'cpython-3[0-9]+' | sort -u | grep -v 'cpython-314' || true)
if [ -n "${WRONG_ABI}" ]; then
    echo "FAIL: found .so files with unexpected ABI tag(s): ${WRONG_ABI}"
    echo "Expected cpython-314 only. Aborting."
    rm -rf "${LAYER_DIR}"
    exit 1
fi
SO_COUNT=$(find "${PYTHON_DIR}" -name '*.so' | wc -l | tr -d ' ')
echo "  OK: ${SO_COUNT} .so files, all cpython-314-aarch64-linux-gnu"

echo ""

# Check unzipped size (Lambda limit: 250MB)
UNZIPPED_SIZE=$(du -sm "${LAYER_DIR}" | cut -f1)
echo "Unzipped size: ${UNZIPPED_SIZE}MB (Lambda limit: 250MB)"

if [ "${UNZIPPED_SIZE}" -gt 250 ]; then
    echo ""
    echo "FAIL: Layer exceeds 250MB! Fall back to container image."
    rm -rf "${LAYER_DIR}"
    exit 1
fi

# Package into ZIP
echo ""
echo "Creating ZIP archive..."
cd "${LAYER_DIR}"
zip -r -q "${OUTPUT_ZIP}" python/
cd "${SCRIPT_DIR}"

ZIP_SIZE=$(du -sm "${OUTPUT_ZIP}" | cut -f1)

echo ""
echo "============================================================"
echo "Lambda Layer built successfully!"
echo "  Output:   ${OUTPUT_ZIP}"
echo "  Zipped:   ${ZIP_SIZE}MB"
echo "  Unzipped: ${UNZIPPED_SIZE}MB"
echo ""
echo "Next: sam build && sam deploy"
echo "============================================================"

# Cleanup build directory
rm -rf "${LAYER_DIR}"
