"""
Week Configuration Reader
Centralized utility to read week values from config file.

This module provides functions to read week values from config/current_week.json,
which is generated by the detect_current_week.py script.

New dual-value system:
- nfl_week: Current NFL week (what week it is)
- through_week: Last week with complete scores (what data we have)
- regular_season_week: Regular season progress (capped at 14)
"""

import json
import logging
from pathlib import Path
from typing import Optional, Dict

logger = logging.getLogger(__name__)


def load_week_config() -> Dict:
    """
    Load the complete week configuration from file.
    
    Returns:
        Dict with nfl_week, through_week, regular_season_week fields
        
    Raises:
        FileNotFoundError: If config file doesn't exist
        ValueError: If config file is invalid
    """
    config_file = Path(__file__).parent.parent / "config" / "current_week.json"
    
    if not config_file.exists():
        error_msg = (
            f"Week config file not found: {config_file}\n"
            f"Please run: python3 scripts/detect_current_week.py"
        )
        logger.error(error_msg)
        raise FileNotFoundError(error_msg)
    
    try:
        with open(config_file, 'r') as f:
            return json.load(f)
    except json.JSONDecodeError as e:
        error_msg = f"Invalid JSON in config file {config_file}: {e}"
        logger.error(error_msg)
        raise ValueError(error_msg)


def get_current_week_from_config() -> int:
    """
    Read current week from centralized config file.
    
    Backward compatible: Returns regular_season_week (or current_week for old format).
    For new code, use get_regular_season_week(), get_nfl_week(), or get_through_week().
    
    Returns:
        Regular season week number (1-14)
        
    Raises:
        FileNotFoundError: If config file doesn't exist
        ValueError: If config file is invalid
    """
    config = load_week_config()
    
    # New format: has regular_season_week
    if 'regular_season_week' in config:
        return int(config['regular_season_week'])
    
    # Old format: fallback to current_week
    if 'current_week' in config:
        return int(config['current_week'])
    
    raise ValueError("Config missing both 'regular_season_week' and 'current_week' fields")


def get_nfl_week() -> int:
    """
    Get current NFL week (what week it is).
    
    Returns:
        NFL week number from Sleeper's 'leg' field
    """
    config = load_week_config()
    
    if 'nfl_week' in config:
        return int(config['nfl_week'])
    
    # Fallback to current_week for backward compatibility
    if 'current_week' in config:
        return int(config['current_week'])
    
    raise ValueError("Config missing 'nfl_week' field")


def get_through_week() -> int:
    """
    Get last week with complete scores (what data we have).
    
    Returns:
        Through week number from Sleeper's 'last_scored_leg' field
    """
    config = load_week_config()
    
    if 'through_week' in config:
        return int(config['through_week'])
    
    # Fallback to current_week for backward compatibility
    if 'current_week' in config:
        return int(config['current_week'])
    
    raise ValueError("Config missing 'through_week' field")


def get_regular_season_week() -> int:
    """
    Get regular season week progress (capped at 14).
    
    Returns:
        Regular season week number (1-14)
    """
    config = load_week_config()
    
    if 'regular_season_week' in config:
        return int(config['regular_season_week'])
    
    # Fallback to current_week capped at 14
    if 'current_week' in config:
        return min(int(config['current_week']), 14)
    
    raise ValueError("Config missing 'regular_season_week' field")


def get_current_week_with_fallback(fallback: Optional[int] = None) -> int:
    """
    Read current week from config with optional fallback.
    
    Attempts to read from config file, but returns fallback value if
    config doesn't exist or is invalid. Useful for scripts that need
    to work even if detect_current_week.py hasn't been run yet.
    
    Args:
        fallback: Week number to use if config unavailable (default: 12)
        
    Returns:
        Current week number from config, or fallback if unavailable
        
    Example:
        >>> week = get_current_week_with_fallback(fallback=11)
        >>> print(f"Current week: {week}")
        Current week: 11  # or config value if available
    """
    if fallback is None:
        fallback = 12
    
    try:
        return get_current_week_from_config()
    except (FileNotFoundError, ValueError) as e:
        logger.warning(
            f"Could not read week config ({e}), using fallback: {fallback}"
        )
        return fallback