"""
Week Configuration Reader
Centralized utility to read current week from config file.

This module provides a simple function to read the validated current week
from the config/current_week.json file, which is generated by the
detect_current_week.py script.
"""

import json
import logging
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)


def get_current_week_from_config() -> int:
    """
    Read current week from centralized config file.
    
    This function reads the week number from config/current_week.json,
    which is generated by the detect_current_week.py script. This ensures
    all scripts use the same validated week number.
    
    Returns:
        Current week number (1-14)
        
    Raises:
        FileNotFoundError: If config file doesn't exist
        ValueError: If config file is invalid or missing week
        
    Example:
        >>> week = get_current_week_from_config()
        >>> print(f"Current week: {week}")
        Current week: 12
    """
    # Config file is in pipeline/config/current_week.json
    config_file = Path(__file__).parent.parent / "config" / "current_week.json"
    
    if not config_file.exists():
        error_msg = (
            f"Week config file not found: {config_file}\n"
            f"Please run: python3 scripts/detect_current_week.py"
        )
        logger.error(error_msg)
        raise FileNotFoundError(error_msg)
    
    try:
        with open(config_file, 'r') as f:
            config_data = json.load(f)
        
        if 'current_week' not in config_data:
            raise ValueError("Config file missing 'current_week' field")
        
        current_week = int(config_data['current_week'])
        
        # Validate week is in reasonable range
        if not 1 <= current_week <= 18:
            logger.warning(
                f"Week {current_week} outside expected range (1-18), "
                f"but using it anyway"
            )
        
        logger.debug(f"Read current week from config: {current_week}")
        return current_week
        
    except json.JSONDecodeError as e:
        error_msg = f"Invalid JSON in config file {config_file}: {e}"
        logger.error(error_msg)
        raise ValueError(error_msg)
    except (KeyError, ValueError, TypeError) as e:
        error_msg = f"Error reading week from config: {e}"
        logger.error(error_msg)
        raise ValueError(error_msg)


def get_current_week_with_fallback(fallback: Optional[int] = None) -> int:
    """
    Read current week from config with optional fallback.
    
    Attempts to read from config file, but returns fallback value if
    config doesn't exist or is invalid. Useful for scripts that need
    to work even if detect_current_week.py hasn't been run yet.
    
    Args:
        fallback: Week number to use if config unavailable (default: 12)
        
    Returns:
        Current week number from config, or fallback if unavailable
        
    Example:
        >>> week = get_current_week_with_fallback(fallback=11)
        >>> print(f"Current week: {week}")
        Current week: 11  # or config value if available
    """
    if fallback is None:
        fallback = 12
    
    try:
        return get_current_week_from_config()
    except (FileNotFoundError, ValueError) as e:
        logger.warning(
            f"Could not read week config ({e}), using fallback: {fallback}"
        )
        return fallback